# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "gendocs"
  CheckDocs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2

    - name: Wiki Checkout
      run: |
        cd $GITHUB_WORKSPACE
        git clone https://github.com/revarbat/BOSL2.wiki.git

    - name: Install OpenSCAD
      run: sudo snap install openscad

    - name: Generating Docs
      run: |
        cd $GITHUB_WORKSPACE
        ./scripts/make_all_docs.sh -i

    - name: Generate Index
      run: |
        cd $GITHUB_WORKSPACE
        ./scripts/genindex.sh

